config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  resources :accounts
  resources :teams, path: 't'

  get 'user/me', to: 'users#me', as: 'my_settings'
  patch 'users/update_me', to: 'users#update_me', as: 'update_my_settings'
  get 'user/password', to: 'users#password', as: 'my_password'
  patch 'user/update_password', to: 'users#update_password', as: 'my_update_password'

  get 's/new/(:date)', to: 'standups#new', as: 'new_standup'
  get 's/edit/(:date)', to: 'standups#edit', as: 'edit_standup'
  resources :standups, path: 's', except: [:new, :edit]

  scope 'account', as: 'account' do
    resources :users
  end

  get 'activity/mine'
  
  get 'activity/feed'

  get 'dates/:date', to: 'dates#update', as: 'update_date'

  root to: 'activity#mine'
end

app/models/standup.rb
class Standup < ApplicationRecord
  belongs_to :user

  validates :user, presence: true

  has_many :task_memberships, dependent: :delete_all
  has_many :tasks, through: :task_memberships
  has_many :dids, -> { where(type: 'Did') }, through: :task_memberships, source: :task
  accepts_nested_attributes_for :dids, reject_if: :all_blank, allow_destroy: true
  has_many :todos, -> { where(type: 'Todo') }, through: :task_memberships, source: :task
  accepts_nested_attributes_for :todos, reject_if: :all_blank, allow_destroy: true
  has_many :blockers, -> { where(type: 'Blocker') }, through: :task_memberships, source: :task
  accepts_nested_attributes_for :blockers, reject_if: :all_blank, allow_destroy: true
end

app/controllers/standups_controller.rb
class StandupsController < ApplicationController
  before_action :set_standup, only: %i[ show edit update destroy ]

  def index
    redirect_to root_path
  end

  def show
  end

  def new
    return if check_for_blank_date
    return if check_for_existence
    @standup = Standup.new
  end

  def edit
    return if check_for_blank_date
    return if chek_for_existence
    @standup = Standup.find_by(user: current_user, standup_date: current_date)
  end

  def create
    @standup = Standup.new(standup_params)
    @standup.user = current_user

    if @standup.save
      redirect_back(
        fallback_location: root_path,
        notice: 'Standup was successfuly created'
      )
    else
      render :new
    end
  end

  def update
    if @standup.update(standup_params)
        redirect_back(
          fallback_location: root_path,
          notice: 'Standup was successfuly created'
        )
    end
  end

  def destroy
    @standup.destroy
    respond_to do |format|
      format.html { redirect_to standups_url, notice: "Standup was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_standup
      @standup = Standup.find(params[:id])
    end

    def standup_params
      params.require(:standup).permit(:standup_date, dids_attributes: %i[id title _destroy],
                                                     todos_attributes: %i[id title _destroy], 
                                                     blockers_attributes: %i[id title _destroy])
    end

    def check_for_blank_date
      if params[:date].blank?
        redirect_to(
          update_date_path(date: Date.today.iso8601, reload_path: "/s/#{action_name}/#{Date.today.iso8601}")
        ) and return true
      end
    end

    def check_for_existence
      standup = Standup.find_by(user: current_user, standup_date: current_date)
      if standup.present? && action_name == 'new'
        redirect_to(edit_standup_path(date: current_date)) and return true
      elsif standup.nil? && action_name == 'edit'
        redirect_to(new_standup_path(date: current_date)) and return true
      end
    end
end

app/helpers/standups_helper.rb
module StandupsHelper
end

app/views/standups/_blocker_fields.html.erb
<div class="nested-fields form-group input-group">
  <%= f.text_field :title, class: 'form-control input-lg', placeholder: 'A thing todo' %>
  <span class="input-group-append">
    <%= link_to_remove_association f, class: 'btn btn-danger btn-flat' do %>
      <i class="fa fa-trash"></i>
    <% end %>
  </span>
</div>

app/views/standups/_did_fields.html.erb
<div class="nested-fields form-group input-group">
  <%= f.text_field :title, class: 'form-control input-lg', placeholder: 'A thing I did' %>
  <span class="input-group-append">
    <%= link_to_remove_association f, class: 'btn btn-danger btn-flat' do %>
      <i class="fa fa-trash"></i>
    <% end %>
  </span>
</div>

app/views/standups/_form.html.erb
<%= form_with model: @standup, id: 'standup-form', html:{class: 'form-horizontal'} do |f| %>
  <%= f.hidden_field :standup_date, value: current_date %>
  <% if @standup.errors.any?%>
    <%= render partial: 'shared/model_errors', locals: {model: @standup} %>
  <% end %>
  <%= render partial: 'layouts/date_change', locals: {reload_path: "/s/#{action_name}"} %>
  <div class="row">
    <div class="col">
      <div class="card">
        <div class="card-header">
          <h3>
            What did you do since your last standup?
          </h3>
        </div>
        <div class="card-body">
          <%= f.fields_for :dids do |did| %>
            <%= render 'did_fields', f: did %>
          <% end %>
          <div class="links" style="width: 40px;">
            <%= link_to_add_association f, :dids, class: 'btn btn-block btn-success btn-flat', style: 'border-radius:50%' do %>
              <i class="fa fa-plus"></i>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <div class="card">
        <div class="card-header">
          <h3>
            What are you doing today?
          </h3>
        </div>
        <div class="card-body">
          <%= f.fields_for :todos do |todo| %>
            <%= render 'todo_fields', f: todo %>
          <% end %>
          <div class="links" style="width: 40px;">
            <%= link_to_add_association f, :todos, class: 'btn btn-block btn-success btn-flat', style: 'border-radius:50%' do %>
              <i class="fa fa-plus"></i>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <div class="card">
        <div class="card-header">
          <h3>
            What is blocking you?
          </h3>
        </div>
        <div class="card-body">
          <%= f.fields_for :blockers do |blocker| %>
            <%= render 'blocker_fields', f: blocker %>
          <% end %>
          <div class="links" style="width: 40px;">
            <%= link_to_add_association f, :blockers, class: 'btn btn-block btn-success btn-flat', style: 'border-radius:50%' do %>
              <i class="fa fa-plus"></i>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2">
      <%= f.submit 'Save', class: ' btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/standups/_todo_fields.html.erb
<div class="nested-fields form-group input-group">
  <%= f.text_field :title, class: 'form-control input-lg', placeholder: 'A thing todo' %>
  <span class="input-group-append">
    <%= link_to_remove_association f, class: 'btn btn-danger btn-flat' do %>
      <i class="fa fa-trash"></i>
    <% end %>
  </span>
</div>

app/views/standups/edit.html.erb
<h1>Editing Standup</h1>

<%= render 'form', standup: @standup %>

<%= link_to 'Show', @standup %> |
<%= link_to 'Back', standups_path %>

app/views/standups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Standups</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Standup date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @standups.each do |standup| %>
      <tr>
        <td><%= standup.user_id %></td>
        <td><%= standup.standup_date %></td>
        <td><%= link_to 'Show', standup %></td>
        <td><%= link_to 'Edit', edit_standup_path(standup) %></td>
        <td><%= link_to 'Destroy', standup, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Standup', new_standup_path %>

app/views/standups/new.html.erb
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
      </div>
    </div>
  </div>
</div>
<section class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-8 offset-2">
        <div class="card">
          <div class="card-header">
            <h4>Add A Standup</h4>
          </div>
        </div>
        <%= render 'form' %>
      </div>
    </div>
  </div>
</section>

app/views/standups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @standup.user_id %>
</p>

<p>
  <strong>Standup date:</strong>
  <%= @standup.standup_date %>
</p>

<%= link_to 'Edit', edit_standup_path(@standup) %> |
<%= link_to 'Back', standups_path %>