config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  resources :accounts
  resources :teams, path: 't'

  get 'user/me', to: 'users#me', as: 'my_settings'
  patch 'users/update_me', to: 'users#update_me', as: 'update_my_settings'
  get 'user/password', to: 'users#password', as: 'my_password'
  patch 'user/update_password', to: 'users#update_password', as: 'my_update_password'

  get 's/new/(:date)', to: 'standups#new', as: 'new_standup'
  get 's/edit/(:date)', to: 'standups#edit', as: 'edit_standup'
  resources :standups, path: 's', except: [:new, :edit]

  scope 'account', as: 'account' do
    resources :users
  end

  get 'activity/mine'
  
  get 'activity/feed'

  get 'dates/:date', to: 'dates#update', as: 'update_date'

  root to: 'activity#mine'
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  attr_accessor :role
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  belongs_to :account, optional: true

  has_many :team_memberships
  has_many :teams, through: :team_memberships
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit destroy update ]
  before_action :set_users, only: %i[ index ]
  load_and_authorize_resource

  def index
    # unless current_user.has_role?('admin', current_user.account) 
    #   redirect_to root_path, notice: 'You are not authorized'
    # end
  end


  def new
    @user = User.new
    set_choices
  end

  def edit
    set_choices
  end

  def me 
    @user = current_user
  end

  def password 
    @user = current_user
  end

  def update_password
    @user = current_user
    respond_to do |format|
      if @user.update(user_password_params)
        bypass_sign_in(@user)
        format.html {
          redirect_to my_password_path,
          notice: 'Password was successfully updated.'
        }
      else
        format.html {render :password}
      end
    end
  end

  def update_me
    @user = current_user
    respond_to do |format|
      if @user.update(user_params)
        format.html do
          redirect_to my_settings_path,
                      notice: 'Your information was successfully updated.'
        end
      else
        format.html { render :me }
      end
    end
  end

  def create
    @user = User.unscoped.new(user_params.except('role'))
    @user.account = current_account
    @user.password = 'password'

    respond_to do |format|
      begin
        if @user.valid? && @user.invite!(current_user)
          @user.add_role user_params[:role].to_sym, current_account
          format.html {
            redirect_to account_users_path,
            notice: 'User was sucessfully invited.'
          }
        else
          set_choices
          format.html { render :new }
        end
      rescue ActiveRecord::RecordNotUnique
        flash[:alert] = 'Email should be unique'
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params.except('role'))
        format.html do
          redirect_to account_users_path,
                      notice: 'User was successfully updated.'
        end
      else
        set_choices
        format.html { render :edit }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { 
        redirect_to account_users_path,
        notice: 'User was successfully removed.'
       }
       format.json { head :no_content }
    end
  end
  

  private

  def set_user
    @user = User.find(params[:id])
  end

  def set_users
    @users = current_account.users
  end

  def set_choices
    @choices = [['Admin', 'admin'], ['User', 'user']]
  end

  def user_password_params
    params.require(:user).permit(:password, :password_confirmation)
  end

  def user_params
    params.require(:user).permit(:name, :email, :role, :time_zone)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1 class="m-0 text-dark">Users</h1>
      </div>
    </div>
  </div>
</div>
<section class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <div class="card">
          <%= form_with(model: @user, url: account_user_path(@user), id: 'edit_user', html: {class: 'form-horizontal'}) do |f| %>
            <div class="card-header">
              <h3 class="card-title">
                Edit User Information
              </h3>
            </div>
            <div class="card-body">
              <% if @user.errors.any? %>
                <div class="alert alert-error alert-block alert-fixed">
                  <h4>
                    <%= "#{pluralize(@user.errors.count, 'error')}" %>
                  </h4>
                  <%= @user.errors.full_messages.map{|msg| content_tag(:li, msg)}.join.html_safe %>
                </div>
              <% end %>
              <%= label_tag 'user[name]', 'Name', class: 'control-label col-lg-2' %>
              <div class="col-lg-10">
                <%= f.text_field :name, {placeholder: "Name", autofocus: true, class: "form-control"} %>
              </div>
              <%= label_tag 'user[email]', 'Email', class: 'control-label col-lg-2' %>
              <div class="col-lg-10">
                <%= f.email_field :email, {placeholder: "Email Address", class: "form-control"} %>
              </div>
              <%= label_tag "user[role]", "Role", class: 'control-label col-lg-2' %>
              <div class="col-lg-10">
                <%= select_tag "user[role]", options_for_select(@choices, 'user'), class: 'form-control' %>
              </div>
            </div>
            <div class="card-footer" style="height: 55px;">
              <span class="pull-right">
                <%= f.submit "Edit User", class: "btn btn-primary" %>
              </span>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/users/index.html.erb
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1 class="m-0 text-dark">Users</h1>
      </div>
    </div>
  </div>
</div>
<section class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <div class="card">
          <div class="card-header">
            <h3 class="card-title">
              <%= "Users in #{current_account.name}" %>
            </h3>
          </div>
          <div class="card-body">
            <div class="table-responsive">
              <table class="table table-striped">
                <thead>
                  <tr>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Status</th>
                    <th>Role</th>
                    <th>Added at</th>
                    <th></th>
                  </tr>
                </thead>
                <tbody>
                  <% @users.each do |user|%>
                    <tr>
                      <td><%= user.name %></td>
                      <td><%= user.email %></td>
                      <td><%= user.accepted_or_not_invited? ? "Active" : "Invited" %></td>
                      <td><%= user.roles&.first&.name&.capitalize %></td>
                      <td><%= user.created_at.strftime('%D') %></td>
                      <td>
                        <%= link_to 'Edit', edit_account_user_path(user), class: 'btn btn-default btn-xs' %>
                        <%= link_to 'Destroy', account_user_path(user), {method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-warning btn-xs'} unless user.id == current_user.id %>
                      </td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div>
          <div class="card-footer" style="height: 55px;">
            <span class="pull-right">
              <a class="btn btn-primary" href="<%= new_account_user_path %>">
                Add User
              </a>
            </span>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/users/me.html.erb
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1 class="m-0 text-dark">Settings</h1>
      </div>
    </div>
  </div>
</div>
<section class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <div class="card">
          <%= form_with(model: @user, url: update_my_settings_path, id: 'edit_my_user', html: {class: 'form-horizontal'}) do |f| %>
            <div class="card-header">
              <h3 class="card-title">
                My Information
              </h3>
            </div>
            <div class="card-body">
              <% if @user.errors.any? %>
                <div class="alert alert-error alert-block alert-fixed">
                  <h4>
                    <%= "#{pluralize(@user.errors.count, 'error')}" %>
                  </h4>
                  <%= @user.errors.full_messages.map{|msg| content_tag(:li, msg)}.join.html_safe %>
                </div>
              <% end %>
              <div class="form-group">
                <%= f.label :name, class: 'control-label col-lg-2' %>
                <div class="col-lg-10">
                  <%= f.text_field :name, {placeholder: "Name", autofocus: true, class: "form-control"} %>
                </div>
              </div>
              <div class="form-group">
                <%= f.label :email, class: 'control-label col-lg-2' %>
                <div class="col-lg-10">
                  <%= f.email_field :email, {placeholder: "Email Address", class: "form-control"} %>
                </div>
              </div>
              <div class="form-group">
                <%= f.label :time_zone, class: 'control-label col-lg-2' %>
                <div class="col-lg-10">
                  <%= f.time_zone_select(:time_zone, ActiveSupport::TimeZone.us_zones, {}, {class: 'form-control'}) %>
                </div>
              </div>
            </div>
            <div class="card-footer" style="height: 55px;">
              <span class="pull-right">
                <%= f.submit "Update My Settings", class: "btn btn-primary" %>
              </span>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/users/new.html.erb
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1 class="m-0 text-dark">Users</h1>
      </div>
    </div>
  </div>
</div>
<section class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <div class="card">
          <%= form_with(model: @user, url: account_users_path, id: 'new_user', html: {class: 'form-horizontal'}) do |f| %>
            <div class="card-header">
              <h3 class="card-title">
                Add A New User
              </h3>
            </div>
            <div class="card-body">
              <% if @user.errors.any? %>
                <div class="alert alert-error alert-block alert-fixed">
                  <h4>
                    <%= "#{pluralize(@user.errors.count, 'error')}" %>
                  </h4>
                  <%= @user.errors.full_messages.map{|msg| content_tag(:li, msg)}.join.html_safe %>
                </div>
              <% end %>
              <%= label_tag 'user[name]', 'Name', class: 'control-label col-lg-2' %>
              <div class="col-lg-10">
                <%= f.text_field :name, {placeholder: "Name", autofocus: true, class: "form-control"} %>
              </div>
              <%= label_tag 'user[email]', 'Email', class: 'control-label col-lg-2' %>
              <div class="col-lg-10">
                <%= f.email_field :email, {placeholder: "Email Address", class: "form-control"} %>
              </div>
              <%= label_tag "user[role]", "Role", class: 'control-label col-lg-2' %>
              <div class="col-lg-10">
                <%= select_tag "user[role]", options_for_select(@choices, 'user'), class: 'form-control' %>
              </div>
            </div>
            <div class="card-footer" style="height: 55px;">
              <span class="pull-right">
                <%= f.submit "Add User", class: "btn btn-primary" %>
              </span>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/users/password.html.erb
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1 class="m-0 text-dark">Settings</h1>
      </div>
    </div>
  </div>
</div>
<section class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <div class="card">
          <%= form_with(model: @user, url: my_update_password_path, id: 'edit_user_password', html: {class: 'form-horizontal'}) do |f| %>
            <div class="card-header">
              <h3 class="card-title">
                Update Password
              </h3>
            </div>
            <div class="card-body">
              <% if @user.errors.any? %>
                <div class="alert alert-error alert-block alert-fixed">
                  <h4>
                    <%= "#{pluralize(@user.errors.count, 'error')}" %>
                  </h4>
                  <%= @user.errors.full_messages.map{|msg| content_tag(:li, msg)}.join.html_safe %>
                </div>
              <% end %>
              <div class="form-group">
                <%= f.label :password, class: 'control-label col-lg-2' %>
                <div class="col-lg-10">
                  <%= f.password_field :password, {placeholder: "Enter Password", autofocus: true, class: "form-control"} %>
                </div>
              </div>
              <div class="form-group">
                <%= f.label :password_confirmation, class: 'control-label col-lg-2' %>
                <div class="col-lg-10">
                  <%= f.password_field :password_confirmation, {placeholder: "Retype Password", class: "form-control"} %>
                </div>
              </div>
            </div>
            <div class="card-footer" style="height: 55px;">
              <span class="pull-right">
                <%= f.submit "Update Password", class: "btn btn-primary" %>
              </span>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>