config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  resources :accounts
  resources :teams, path: 't'

  get 'user/me', to: 'users#me', as: 'my_settings'
  patch 'users/update_me', to: 'users#update_me', as: 'update_my_settings'
  get 'user/password', to: 'users#password', as: 'my_password'
  patch 'user/update_password', to: 'users#update_password', as: 'my_update_password'

  get 's/new/(:date)', to: 'standups#new', as: 'new_standup'
  get 's/edit/(:date)', to: 'standups#edit', as: 'edit_standup'
  resources :standups, path: 's', except: [:new, :edit]

  scope 'account', as: 'account' do
    resources :users
  end

  get 'activity/mine'
  
  get 'activity/feed'

  get 'dates/:date', to: 'dates#update', as: 'update_date'

  root to: 'activity#mine'
end

app/views/layouts/_date_change.html.erb
    
<div class="row">
  <div class="col-lg-1 offset-lg-2 col-md-2 offset-md-1 col-sm-2 offset-sm-1">
    <%= link_to update_date_path(date: Date.parse(current_date) - 1.day), id: 'date_backwards' do %>
      <div class="card">
        <div class="card-body text-center">
          <i class="fa fa-arrow-left fa-2x"></i>
        </div>
      </div>
    <% end %>
  </div>
  <div class="col-lg-6 col-md-5 col-sm-5">
    <div class="card cursor" id="datePicker">
      <div class="card-body text-center">
        <input id="datePickerInput" type="text" name="current_date" value=current_date style="visibility:hidden;width:.5px;" />
        <i class="fa fa-calendar fa-2x"></i>
        <h3 style="margin-left:10px;display:inline;font-weight:100;">
          <%= Date.parse(current_date).strftime("%a, %b #{Date.parse(current_date).day.ordinalize}") %>
        </h3>
      </div>
    </div>
  </div>
  <div class="col-lg-1 col-lg-offset-2 col-md-2 col-md-offset-1 col-sm-2 col-sm-offset-1">
    <%= link_to update_date_path(date: Date.parse(current_date) + 1.day), id: 'date_forward' do %>
      <div class="card">
        <div class="card-body text-center">
          <i class="fa fa-arrow-right fa-2x"></i>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="main-footer full-footer">
  <strong>Copyright © 2020 Your Stuff.</strong>
  All rights reserved.
</footer>

app/views/layouts/_header.html.erb
<nav class="main-header navbar navbar-expand navbar-white navbar-light border-bottom\
<%="#{'no-team' unless @team.present? && !@team.id.nil?}" %>">
  <ul class="navbar-nav">
    <% if @team.present? && !@team.id.nil? %>
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#">
          <i class="fas fa-bars"></i>
        </a>
      </li>
    <% end %>
    <li class="nav-item d-none d-sm-inline-block">
      <a href="/t" class="nav-link">Teams</a>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
      <a href="/s" class="nav-link">Standups</a>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
      <a href='/s/new/<%="#{Date.today.iso8601}"%>' class="nav-link standup">
        Submit a Standup
      </a>
    </li>
  </ul>
  <ul class="navbar-nav ml-auto">
    <li class="nav-item dropdown">
      <a class="nav-link" data-toggle="dropdown" href="#">
        <i class="far fa-bell"></i>
        <span class="badge badge-warning navbar-badge">15</span>
      </a>
      <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
        <span class="dropdown-item dropdown-header">15 Notifications</span>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item">
          <i class="fas fa-envelope mr-2"></i> 4 new messages
          <span class="float-right text-muted text-sm">3 mins</span>
        </a>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item">
          <i class="fas fa-users mr-2"></i> 8 friend requests
          <span class="float-right text-muted text-sm">12 hours</span>
        </a>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item">
          <i class="fas fa-file mr-2"></i> 3 new reports
          <span class="float-right text-muted text-sm">2 days</span>
        </a>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
      </div>
    </li>
    <li class="nav-item dropdown user-menu">
      <a class="nav-link" data-toggle="dropdown" href="#">
        <img class="user-image" alt="User Image" src='<%="#{gravatar_image_url(current_user.email, size: 25, secure:false )} "%>' class="fas fa-th-large"></img>
      <span class="hidden-xs">
        <%= current_user.name %>
      </span>
    </a>
    <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
      <span class="dropdown-item dropdown-header">
        <%= current_user.name %>
      </span>
      <div class="dropdown-divider"></div>
      <a href="/user/me" class="dropdown-item">
        Profile
      </a>
      <a href="/account/users" class="dropdown-item">
        Settings
      </a>
      <div class="dropdown-divider"></div>
      <%= link_to(destroy_user_session_path, :method => :delete, class: 'dropdown-item') do %>
        <i class="fas fa-sign-out-alt"></i> Log out
      <% end %>
    </div>
  </li>
</ul>
</nav>

app/views/layouts/_sidebar.html.erb
<% if @team.present? && !@team.id.nil? %>
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <a href="/" class="brand-link">
      <span class="brand-text font-weight-light">Standup App</span>
    </a>
    <div class="slimScrollDiv" style="position: relative; overflow: hidden; width: auto; height: 652px;">
      <div class="sidebar" style="min-height: 652px; overflow: hidden; width: auto; height: 652px;">
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
          <div class="image">
            <h3 class="header-circ">
              <%= @team&.name[0]&.upcase %>
            </h3>
          </div>
          <div class="info" style="vertical-align: middle; margin-top: 5px;">
            <a href="#"><%= @team.name %></a>
          </div>
        </div>
        <nav class="mt-2">
          <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
            <li class="nav-header">Overview</li>
            <li class="nav-item">
              <%= link_to team_path(@team), {class: 'nav-link', id: "edit_#{@team.id}_sidebar"} do %>
                <i class="fas fa-tachometer-alt"></i>
                <p> Details</p>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to edit_team_path(@team), {class: 'nav-link', id: "edit_#{@team.id}_sidebar"} do %>
                <i class="fas fa-cog"></i>
                <p> Settings</p>
              <% end %>
            </li>
            <li class="nav-item has-treeview menu-open">
              <a href="#" class="nav-link">
                <p>
                  Standups
                  <i class="right fas fa-angle-left"></i>
                </p>
              </a>
              <ul class="nav nav-treeview">
                <li class="nav-item">
                  <a href=<%="/t/#{@team.id}/s"%> class="nav-link">
                    <i class="fas fa-child"></i>
                    <p>View</p>
                  </a>
                </li>
              </ul>
            </li>
          </ul>
        </nav>
      </div>
    </aside>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Standup App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="sidebar-mini">
    <div class="wrapper">
      <%= render partial: "layouts/header" %>
      <%= render partial: "layouts/sidebar" %>
      <div class='content-wrapper <%="#{'no-team' unless @team.present? && !@team.id.nil?}" %>'>
        <div class="content-wrapper">
          <%= flash_messages %>
          <%= yield %>
        </div>
        <%= render partial: "layouts/footer" %>
      </div>
    </body>
  </html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Standup App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/68cb87669c.js"></script>
  </head>
  <body class="login-page">
    <%= flash_messages %>
    <%= yield %>
  </body>
</html>